/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.habanahotel;

import java.awt.Font;
import javax.swing.table.JTableHeader;
import static com.mycompany.habanahotel.Reservas.*;
import java.awt.Color;

/**
 * Clase que representa el cuadro de diálogo para listar las reservas en el
 * hotel. Permite mostrar y cambiar el estilo de la tabla de reservas. Extiende
 * javax.swing.JDialog.
 *
 * @author José Carlos Lucientes Casaos
 */
public class Listado extends javax.swing.JDialog {

    private int styleCounter = 0; // Variable de contador para alternar estilos

    /**
     * Crea una nueva instancia de Listado. Inicializa los componentes y
     * configura la tabla.
     */
    public Listado() {
        //super(parent, modal);
        initComponents();
        cambiarCabeceraTabla();
        cargarReservas();
    }

    /**
     * Carga las reservas desde la matriz de datos en la tabla. Recorre la
     * matriz hasta encontrar una celda vacía.
     */
    public void cargarReservas() {

        boolean seguirBuscando = true;
        int i = 0;

        //recorrer la matriz para ver las reservas en la tabla
        while (seguirBuscando) {
            if (matriz[i][CONST_NOMBRE] == null) {
                seguirBuscando = false;
            } else {
                tblListado.setValueAt(matriz[i][CONST_NOMBRE], i, CONST_NOMBRE);
                tblListado.setValueAt(matriz[i][CONST_TELEFONO], i, CONST_TELEFONO);
                tblListado.setValueAt(matriz[i][CONST_TIPOEVENTO], i, CONST_TIPOEVENTO);
                tblListado.setValueAt(matriz[i][CONST_JORNADAS], i, CONST_JORNADAS);
                tblListado.setValueAt(matriz[i][CONST_HABITACIONES], i, CONST_HABITACIONES);
                tblListado.setValueAt(matriz[i][CONST_FECHA], i, CONST_FECHA);
                tblListado.setValueAt(matriz[i][CONST_COCINA], i, CONST_COCINA);
                tblListado.setValueAt(matriz[i][CONST_PERSONAS], i, CONST_PERSONAS);
                i = i + 1;
            }
        }
    }

    /**
     * Cambia el estilo de la cabecera de la tabla. Establece una fuente
     * específica para la cabecera.
     */
    public void cambiarCabeceraTabla() {
        // formato tabla 
        JTableHeader th;
        th = tblListado.getTableHeader();

        Font fuente = new Font("Arial Rounded MT Bold", Font.BOLD, 14);
        th.setFont(fuente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sclListado = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado Reservas");
        setBackground(new java.awt.Color(255, 255, 255));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        sclListado.setPreferredSize(new java.awt.Dimension(938, 141));

        tblListado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblListado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Telefono", "Evento", "Jornadas", "Habitaciones", "Fecha", "Cocina", "Personas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListado.setToolTipText("Tabla Reservas");
        tblListado.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tblListado.setInheritsPopupMenu(true);
        tblListado.setMaximumSize(new java.awt.Dimension(950, 110));
        tblListado.setMinimumSize(new java.awt.Dimension(950, 110));
        tblListado.setName("Listado Reservas"); // NOI18N
        tblListado.setPreferredSize(new java.awt.Dimension(950, 900));
        tblListado.setRowHeight(30);
        tblListado.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblListado.setSelectionForeground(new java.awt.Color(0, 0, 0));
        sclListado.setViewportView(tblListado);

        jButton1.setText("Estilos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStyles(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sclListado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sclListado, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción realizada cuando se presiona el botón "Estilos". Alterna entre
     * diferentes estilos de la tabla.
     *
     * @param evt El evento de acción generado al presionar el botón.
     */
    private void BtnStyles(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStyles
        cambiarEstiloTabla();
    }//GEN-LAST:event_BtnStyles
    /**
     * Cambia el estilo de la tabla, alternando entre diferentes fuentes y
     * colores. Cada llamada alterna al siguiente estilo en el ciclo.
     */
    public void cambiarEstiloTabla() {
        JTableHeader th = tblListado.getTableHeader();
        Font fuente;
        Color headerColor;
        Color rowColor;

        // Alternar entre diferentes estilos
        switch (styleCounter) {
            case 0:
                fuente = new Font("Arial Rounded MT Bold", Font.BOLD, 14);
                headerColor = Color.LIGHT_GRAY;
                rowColor = Color.WHITE;
                break;
            case 1:
                fuente = new Font("Verdana", Font.ITALIC, 12);
                headerColor = Color.DARK_GRAY;
                rowColor = Color.LIGHT_GRAY;
                break;
            case 2:
                fuente = new Font("SansSerif", Font.PLAIN, 16);
                headerColor = Color.BLUE;
                rowColor = Color.CYAN;
                break;
            default:
                fuente = new Font("Arial Rounded MT Bold", Font.BOLD, 14);
                headerColor = Color.LIGHT_GRAY;
                rowColor = Color.WHITE;
                styleCounter = 0; // Resetear contador
                break;
        }

        // Aplicar el estilo seleccionado
        th.setFont(fuente);
        th.setBackground(headerColor);
        tblListado.setBackground(rowColor);

        // Incrementar el contador
        styleCounter++;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane sclListado;
    public javax.swing.JTable tblListado;
    // End of variables declaration//GEN-END:variables
}
