/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.habanahotel;

/**
 * Clase que representa la ventana principal de la aplicación del hotel Habana.
 * Permite realizar nuevas reservas y ver las reservas existentes. Extiende
 * javax.swing.JDialog.
 *
 * @autor José Carlos Lucientes Casaos
 */
public class Principal extends javax.swing.JDialog {

    /**
     * Crea una nueva instancia de Principal.
     *
     * @param parent El marco principal de la aplicación.
     * @param modal Indica si la ventana es modal.
     */
    public Principal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        pnlNuevaVerReservas = new javax.swing.JPanel();
        btnNuevaReserva = new javax.swing.JButton();
        btnVerReservas = new javax.swing.JButton();
        mnbrReserva = new javax.swing.JMenuBar();
        mnReserva = new javax.swing.JMenu();
        mnVerReservas = new javax.swing.JMenu();
        mnNuevaReserva = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelCuba.jpg"))); // NOI18N
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 900, 490));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 350));

        pnlNuevaVerReservas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNuevaReserva.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        btnNuevaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevo.png"))); // NOI18N
        btnNuevaReserva.setText("NUEVA RESERVA");
        btnNuevaReserva.setToolTipText("HACER NUEVA RESERVA");
        btnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaReservaActionPerformed(evt);
            }
        });
        pnlNuevaVerReservas.add(btnNuevaReserva);

        btnVerReservas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        btnVerReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver.png"))); // NOI18N
        btnVerReservas.setText("VER RESERVAS");
        btnVerReservas.setToolTipText("VER RESERVAS");
        btnVerReservas.setName(""); // NOI18N
        btnVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReservasActionPerformed(evt);
            }
        });
        pnlNuevaVerReservas.add(btnVerReservas);

        getContentPane().add(pnlNuevaVerReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 690, -1));

        mnReserva.setText("Reserva");

        mnVerReservas.setText("Ver Reservas");
        mnVerReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnVerReservasMouseClicked(evt);
            }
        });
        mnVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVerReservasActionPerformed(evt);
            }
        });
        mnReserva.add(mnVerReservas);

        mnNuevaReserva.setText("Nueva Reserva");
        mnNuevaReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnNuevaReservaMouseClicked(evt);
            }
        });
        mnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNuevaReservaActionPerformed(evt);
            }
        });
        mnReserva.add(mnNuevaReserva);

        mnbrReserva.add(mnReserva);

        setJMenuBar(mnbrReserva);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción realizada cuando se hace clic en "Ver Reservas" en el menú.
     * Muestra la ventana de listado de reservas.
     *
     * @param evt El evento de clic del ratón.
     */
    private void mnVerReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnVerReservasMouseClicked
        Listado listado = new Listado();
        listado.setVisible(true);
    }//GEN-LAST:event_mnVerReservasMouseClicked

    private void mnVerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVerReservasActionPerformed
        // Método vacío, no se realiza ninguna acción aquí.
    }//GEN-LAST:event_mnVerReservasActionPerformed
    /**
     * Acción realizada cuando se hace clic en "Nueva Reserva" en el menú.
     * Muestra la ventana de creación de nueva reserva.
     *
     * @param evt El evento de clic del ratón.
     */
    private void mnNuevaReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnNuevaReservaMouseClicked
        Reservas reservas = new Reservas(new javax.swing.JFrame(), false);
        reservas.addWindowListener(new java.awt.event.WindowAdapter() {
        });
        reservas.setAlwaysOnTop(true);
        reservas.setVisible(true);
    }//GEN-LAST:event_mnNuevaReservaMouseClicked

    private void mnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNuevaReservaActionPerformed
        // Método vacío, no se realiza ninguna acción aquí.
    }//GEN-LAST:event_mnNuevaReservaActionPerformed

    /**
     * Acción realizada cuando se presiona el botón "NUEVA RESERVA". Muestra la
     * ventana de creación de nueva reserva.
     *
     * @param evt El evento de acción generado al presionar el botón.
     */
    private void btnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaReservaActionPerformed
        // TODO add your handling code here:
        Reservas reservas = new Reservas(new javax.swing.JFrame(), false);
        reservas.addWindowListener(new java.awt.event.WindowAdapter() {
        });
        reservas.setAlwaysOnTop(true);
        reservas.setVisible(true);
    }//GEN-LAST:event_btnNuevaReservaActionPerformed
    /**
     * Acción realizada cuando se presiona el botón "VER RESERVAS". Muestra la
     * ventana de listado de reservas.
     *
     * @param evt El evento de acción generado al presionar el botón.
     */
    private void btnVerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReservasActionPerformed
        // TODO add your handling code here:
        Listado listado = new Listado();
        listado.setVisible(true);
        //JOptionPane.showMessageDialog(null, matriz[0][0].toString());
    }//GEN-LAST:event_btnVerReservasActionPerformed

    /**
     * Método principal para ejecutar la aplicación.
     *
     * @param args Los argumentos de la línea de comandos.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal dialog = new Principal(new javax.swing.JFrame(), false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                //dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNuevaReserva;
    public javax.swing.JButton btnVerReservas;
    private javax.swing.JLabel lblFondo;
    public javax.swing.JMenu mnNuevaReserva;
    public javax.swing.JMenu mnReserva;
    public javax.swing.JMenu mnVerReservas;
    private javax.swing.JMenuBar mnbrReserva;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlNuevaVerReservas;
    // End of variables declaration//GEN-END:variables
}
