/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.habanahotel;

import javax.swing.JOptionPane;

/**
 * La clase Reservas representa un diálogo para gestionar las reservas en el
 * hotel Habana. Permite al usuario ingresar y gestionar datos relacionados con
 * reservas, como nombre, teléfono, tipo de evento, fecha del evento, tipo de
 * cocina y número de personas.
 *
 * @author José Carlos Lucientes Casaos
 */
public class Reservas extends javax.swing.JDialog {

    //constantes para identificar el campo dentro de la matriz
    static int CONST_NOMBRE = 0;
    static int CONST_TELEFONO = 1;
    static int CONST_TIPOEVENTO = 2;
    static int CONST_JORNADAS = 3;
    static int CONST_HABITACIONES = 4;
    static int CONST_FECHA = 5;
    static int CONST_COCINA = 6;
    static int CONST_PERSONAS = 7;

    // declaracion de matriz / array para almacenar las reservas
    static String matriz[][] = new String[10][10];

    /**
     * Crea una nueva instancia de Reservas.
     *
     * @param parent el JFrame padre del diálogo
     * @param modal indica si el diálogo es modal
     */
    public Reservas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Constructor sin parámetros que lanza una excepción.
     *
     * @throws UnsupportedOperationException cuando se invoca este constructor
     */
    Reservas() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosReserva = new javax.swing.JPanel();
        lblDatosReserva = new javax.swing.JLabel();
        pnlGuardarBorrar = new javax.swing.JPanel();
        btnBorrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlNombreTelefono = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        pnlFechaEvento = new javax.swing.JPanel();
        lblFechaEvento = new javax.swing.JLabel();
        cldCalendario = new com.toedter.calendar.JDateChooser();
        pnlTipoCocina = new javax.swing.JPanel();
        lblTipoCocina = new javax.swing.JLabel();
        cmbTipoCocina = new javax.swing.JComboBox<>();
        lblNunPersonas = new javax.swing.JLabel();
        txtNumPersonas = new javax.swing.JSpinner();
        pnlTipoEvento = new javax.swing.JPanel();
        lblTipoEvento = new javax.swing.JLabel();
        cmbEvento = new javax.swing.JComboBox<>();
        lblJornadas = new javax.swing.JLabel();
        txtJornadas = new javax.swing.JSpinner();
        lblHabitaciones = new javax.swing.JLabel();
        chkHabitaciones = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDatosReserva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDatosReserva.setToolTipText("DATOS RESERVA");

        lblDatosReserva.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblDatosReserva.setText("DATOS RESERVA");
        lblDatosReserva.setToolTipText("DATOS RESERVA");

        javax.swing.GroupLayout pnlDatosReservaLayout = new javax.swing.GroupLayout(pnlDatosReserva);
        pnlDatosReserva.setLayout(pnlDatosReservaLayout);
        pnlDatosReservaLayout.setHorizontalGroup(
            pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosReservaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblDatosReserva)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlDatosReservaLayout.setVerticalGroup(
            pnlDatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosReservaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDatosReserva))
        );

        pnlGuardarBorrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlGuardarBorrar.setInheritsPopupMenu(true);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del.png"))); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sav.png"))); // NOI18N
        btnGuardar.setLabel("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGuardarBorrarLayout = new javax.swing.GroupLayout(pnlGuardarBorrar);
        pnlGuardarBorrar.setLayout(pnlGuardarBorrarLayout);
        pnlGuardarBorrarLayout.setHorizontalGroup(
            pnlGuardarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardarBorrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(7, 7, 7)
                .addComponent(btnGuardar)
                .addGap(6, 6, 6))
        );
        pnlGuardarBorrarLayout.setVerticalGroup(
            pnlGuardarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardarBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGuardarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.getAccessibleContext().setAccessibleDescription("");

        pnlNombreTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblNombre.setText("NOMBRE:");
        lblNombre.setToolTipText("NOMBRE");

        lblTelefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblTelefono.setText("TELEFONO:");
        lblTelefono.setToolTipText("TELEFONO");

        txtNombre.setToolTipText("Indique nombre completo");
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtTelefono.setToolTipText("Indique telefono de contacto");
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNombreTelefonoLayout = new javax.swing.GroupLayout(pnlNombreTelefono);
        pnlNombreTelefono.setLayout(pnlNombreTelefonoLayout);
        pnlNombreTelefonoLayout.setHorizontalGroup(
            pnlNombreTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNombreTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNombreTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlNombreTelefonoLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(36, 36, 36)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNombreTelefonoLayout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addGap(21, 21, 21)
                        .addComponent(txtTelefono)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNombreTelefonoLayout.setVerticalGroup(
            pnlNombreTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNombreTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNombreTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlNombreTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFechaEvento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlFechaEvento.setForeground(new java.awt.Color(0, 51, 51));
        pnlFechaEvento.setToolTipText("");
        pnlFechaEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblFechaEvento.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblFechaEvento.setText("FECHA EVENTO:");
        lblFechaEvento.setToolTipText("FECHA EVENTO");

        cldCalendario.setToolTipText("Indica fecha del evento");
        cldCalendario.setName("jdtCalendario"); // NOI18N

        javax.swing.GroupLayout pnlFechaEventoLayout = new javax.swing.GroupLayout(pnlFechaEvento);
        pnlFechaEvento.setLayout(pnlFechaEventoLayout);
        pnlFechaEventoLayout.setHorizontalGroup(
            pnlFechaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechaEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaEvento)
                .addGap(47, 47, 47)
                .addComponent(cldCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFechaEventoLayout.setVerticalGroup(
            pnlFechaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFechaEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cldCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(lblFechaEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlTipoCocina.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTipoCocina.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblTipoCocina.setText("TIPO DE COCINA:");
        lblTipoCocina.setToolTipText("TIPO DE COCINA");

        cmbTipoCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "BUFE", "CARTA", "CITA CON EL CHEF", "NO PRECISA", " ", " " }));
        cmbTipoCocina.setToolTipText("Indica tipo de cocina");
        cmbTipoCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCocinaActionPerformed(evt);
            }
        });

        lblNunPersonas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblNunPersonas.setText("Nº PERSONAS:");
        lblNunPersonas.setToolTipText("Nº PERSONAS");

        txtNumPersonas.setToolTipText("Indica numero de personas");

        javax.swing.GroupLayout pnlTipoCocinaLayout = new javax.swing.GroupLayout(pnlTipoCocina);
        pnlTipoCocina.setLayout(pnlTipoCocinaLayout);
        pnlTipoCocinaLayout.setHorizontalGroup(
            pnlTipoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoCocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoCocina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNunPersonas)
                .addGap(18, 18, 18)
                .addComponent(txtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTipoCocinaLayout.setVerticalGroup(
            pnlTipoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoCocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTipoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCocina)
                    .addComponent(cmbTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNunPersonas)
                    .addComponent(txtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTipoEvento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTipoEvento.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblTipoEvento.setText("TIPO EVENTO:");
        lblTipoEvento.setToolTipText("TIPO EVENTO");

        cmbEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "BANQUETE", "JORNADA", "CONGRESO" }));
        cmbEvento.setSelectedItem("");
        cmbEvento.setToolTipText("Seleciona Tipo Evento");
        cmbEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEventoActionPerformed(evt);
            }
        });

        lblJornadas.setText("JORNADAS:");
        lblJornadas.setToolTipText("JORNADAS");
        lblJornadas.setEnabled(false);

        txtJornadas.setToolTipText("Indica numero de jornadas");
        txtJornadas.setEnabled(false);

        lblHabitaciones.setText("REQUIERE HABITACIONES:");
        lblHabitaciones.setToolTipText("REQUIERE HABITACIONES");
        lblHabitaciones.setEnabled(false);

        chkHabitaciones.setToolTipText("Indica si requiere habitaciones");
        chkHabitaciones.setEnabled(false);
        chkHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHabitacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTipoEventoLayout = new javax.swing.GroupLayout(pnlTipoEvento);
        pnlTipoEvento.setLayout(pnlTipoEventoLayout);
        pnlTipoEventoLayout.setHorizontalGroup(
            pnlTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTipoEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoEvento)
                .addGap(18, 18, 18)
                .addComponent(cmbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTipoEventoLayout.createSequentialGroup()
                        .addComponent(lblJornadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTipoEventoLayout.createSequentialGroup()
                        .addComponent(lblHabitaciones)
                        .addGap(18, 18, 18)
                        .addComponent(chkHabitaciones)))
                .addGap(25, 25, 25))
        );
        pnlTipoEventoLayout.setVerticalGroup(
            pnlTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoEventoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkHabitaciones)
                    .addGroup(pnlTipoEventoLayout.createSequentialGroup()
                        .addGroup(pnlTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJornadas)
                            .addComponent(txtJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTipoEventoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTipoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTipoEvento)
                                    .addComponent(cmbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlTipoEventoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblHabitaciones)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlGuardarBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlTipoEvento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlNombreTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlFechaEvento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlTipoCocina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(pnlDatosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlDatosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlNombreTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGuardarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // Método vacío, no se realiza ninguna acción aquí.
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // Método vacío, no se realiza ninguna acción aquí.
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void cmbTipoCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCocinaActionPerformed
        // Método vacío, no se realiza ninguna acción aquí.
    }//GEN-LAST:event_cmbTipoCocinaActionPerformed
    /**
     * Maneja el evento de acción cuando se selecciona un tipo de evento.
     *
     * @param evt el evento que desencadena esta acción.
     */
    private void cmbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEventoActionPerformed
        //habilita y deshabilita las opciones de congreo
        if (cmbEvento.getSelectedItem().toString().equalsIgnoreCase("CONGRESO")) {
            lblJornadas.setEnabled(true);
            txtJornadas.setEnabled(true);
            lblHabitaciones.setEnabled(true);
            chkHabitaciones.setEnabled(true);

        } else {
            chkHabitaciones.setSelected(false);
            txtJornadas.setValue(0);
            lblJornadas.setEnabled(false);
            txtJornadas.setEnabled(false);
            lblHabitaciones.setEnabled(false);
            chkHabitaciones.setEnabled(false);

        }
    }//GEN-LAST:event_cmbEventoActionPerformed


    private void chkHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHabitacionesActionPerformed
        // Método vacío, no se realiza ninguna acción aquí.
    }//GEN-LAST:event_chkHabitacionesActionPerformed
    /**
     * Maneja el evento de acción cuando se hace clic en el botón "Borrar".
     *
     * @param evt el evento que desencadena esta acción.
     */
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        //borra los campos 
        txtNombre.setText("");
        txtTelefono.setText("");
        cmbEvento.setSelectedIndex(0);
        chkHabitaciones.setSelected(false);
        txtJornadas.setValue(0);
        cmbTipoCocina.setSelectedIndex(0);
        txtNumPersonas.setValue(0);
        cldCalendario.setDate(null);
    }//GEN-LAST:event_btnBorrarActionPerformed
    /**
     * Método público que encapsula la acción de borrar campos.
     */
    public void triggerBorrarAction() {
        btnBorrarActionPerformed(null); // método público que encapsule la llamada a btnBorrarActionPerformed
    }

    /**
     * Maneja el evento de acción cuando se hace clic en el botón "Guardar".
     *
     * @param evt el evento que desencadena esta acción.
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        boolean seguirBuscando = true;
        int i = 0;
        //validaciones de campos no vacios, indica mensaje 
        if (txtNombre.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Has de indicar un nombre");
        } else if (txtTelefono.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Has de indicar un telefono");
        } else if (cmbEvento.getSelectedItem().toString().equalsIgnoreCase("Selecciona")) {
            JOptionPane.showMessageDialog(this, "Has de indicar un tipo de evento");
        } else if (txtJornadas.getValue().equals(0) && cmbEvento.getSelectedItem().toString().equalsIgnoreCase("CONGRESO")) {
            JOptionPane.showMessageDialog(this, "Has de indicar el numero de jornadas");
        } else if (cldCalendario.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Has de indicar una fecha");
        } else if (cmbTipoCocina.getSelectedItem().toString().equalsIgnoreCase("Selecciona")) {
            JOptionPane.showMessageDialog(this, "Has de indicar tipo de cocina");
        } else if (txtNumPersonas.getValue().equals(0)) {
            JOptionPane.showMessageDialog(this, "Has de indicar el numero de personas");
        } else {

            //recorremos el array para obtener el ultimo resgistro introducido
            while (seguirBuscando) {
                if (matriz[i][CONST_NOMBRE] == null) {
                    seguirBuscando = false;
                } else {
                    i = i + 1;
                }
            }
            // Guarda el valor en el array de reservas
            matriz[i][CONST_NOMBRE] = txtNombre.getText();
            matriz[i][CONST_TELEFONO] = txtTelefono.getText();
            matriz[i][CONST_TIPOEVENTO] = cmbEvento.getSelectedItem().toString();
            matriz[i][CONST_JORNADAS] = txtJornadas.getValue().toString();
            if (chkHabitaciones.isSelected()) {
                matriz[i][CONST_HABITACIONES] = "SI";
            } else {
                matriz[i][CONST_HABITACIONES] = "NO";
            }
            matriz[i][CONST_FECHA] = cldCalendario.getDate().toString();
            matriz[i][CONST_COCINA] = cmbTipoCocina.getSelectedItem().toString();
            matriz[i][CONST_PERSONAS] = txtNumPersonas.getValue().toString();
            //aviso para indicar que se ha guaradado correctamente
            JOptionPane.showMessageDialog(this, "La reserva se ha guardado correctamente");
            //borra y/o vacia los campos al guardar la reserva 
            txtNombre.setText("");
            txtTelefono.setText("");
            cmbEvento.setSelectedIndex(0);
            cmbTipoCocina.setSelectedIndex(0);
            txtNumPersonas.setValue(0);
            cldCalendario.setDate(null);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    /**
     * Método público que encapsula la acción de guardar una reserva.
     */
    public void triggerGuardarAction() {
        btnGuardarActionPerformed(null); // método público que encapsule la llamada a btnGuardarActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JCheckBox chkHabitaciones;
    public com.toedter.calendar.JDateChooser cldCalendario;
    public javax.swing.JComboBox<String> cmbEvento;
    public javax.swing.JComboBox<String> cmbTipoCocina;
    private javax.swing.JLabel lblDatosReserva;
    private javax.swing.JLabel lblFechaEvento;
    public javax.swing.JLabel lblHabitaciones;
    public javax.swing.JLabel lblJornadas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNunPersonas;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoCocina;
    private javax.swing.JLabel lblTipoEvento;
    private javax.swing.JPanel pnlDatosReserva;
    private javax.swing.JPanel pnlFechaEvento;
    private javax.swing.JPanel pnlGuardarBorrar;
    private javax.swing.JPanel pnlNombreTelefono;
    private javax.swing.JPanel pnlTipoCocina;
    private javax.swing.JPanel pnlTipoEvento;
    public javax.swing.JSpinner txtJornadas;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JSpinner txtNumPersonas;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
